include:
  - project: 'developerdurp/yml'
    ref: main
    file: 'pipelines/build-container.yml'

default:
  image: dtzar/helm-kubectl
  before_script:
    - 'helm repo add --username gitlab-ci-token --password ${CI_JOB_TOKEN} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable'
stages:
  - build
upload:
  stage: upload
  script:
    - helm package ./charts/durpapi
    - 'helm plugin install https://github.com/chartmuseum/helm-push.git'
    - 'helm push ./durpapi-0.1.0.tgz ${CI_PROJECT_NAME}'
