apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.deployment.hpa.minReplicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image }}:{{ default .Chart.Version .Values.deployment.tag }}"
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}   
        readinessProbe:
          httpGet:
            path: /api/v1/health/getHealth
            port: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/health/getHealth
            port: 8080
        startupProbe:
          httpGet:
            path: /api/v1/health/getHealth
            port: 8080
        ports:
        - name: http
          containerPort: {{ .Values.service.targetport }}
        env:
          - name: host
            value: {{ .Values.ingress.host }}
          - name: version
            value: {{ default .Chart.Version .Values.deployment.tag }}
        envFrom:
        - secretRef:
            name: {{ .Values.deployment.secretfile }} 
