apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image }}:{{ default .Chart.Version .Values.deployment.tag }}"
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}       
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        envFrom:
        - secretRef:
            name: {{ .Values.deployment.secretfile }} 