apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: durpapi
  name: durpapi
  labels:
    app: durpapi
spec:
  selector:
    matchLabels:
      app: durpapi
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: durpapi
    spec:
      containers:
      - name: durpapi
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}       
        ports:
        - name: http
          containerPort: http
        envFrom:
        - secretRef:
            name: {{ .Values.deployment.secretfile }} 