apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: durpapi-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterissuer }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: durpapi
            port: 
              number: 80         
  tls:
    - hosts: 
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls }}
