stages:
  - deploy
  - staging
  - production

include:
  - project: "developerdurp/yml"
    ref: "main"
    file:
      - "jobs/version.yml"
      - "jobs/gitlab.yml"

variables:
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  UPLOAD_PACKAGE: "false"
  PROJECT_NAME: $CI_PROJECT_NAME

version:
  extends: .version
  stage:
    .pre

    #build:
    #  stage: deploy
    #  allow_failure: false
    #  trigger:
    #    include:
    #    - project: 'developerdurp/yml'
    #      ref: 'main'
    #      file:
    #        - 'pipelines/go-build.yml'
    #    strategy: depend
    #  rules:
    #    - exists:
    #      - "go.mod"

generate-config-staging:
  extends: .generate-config
  stage: staging
  variables:
    ENVIRONMENT: "staging"

child-pipeline-staging:
  stage: staging
  needs:
    - job: generate-config-staging
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config-staging

generate-config-production:
  extends: .generate-config
  stage: production
  when: manual
  needs:
    - job: version
      artifacts: true
    - job: generate-config-staging
    - job: child-pipeline-staging
  variables:
    ENVIRONMENT: "production"

child-pipeline-production:
  stage: production
  needs:
    - job: generate-config-production
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config-production
