stages:
  - build
  - release

include:
  - project: "developerdurp/yml"
    ref: "main"
    file:
      - "jobs/version.yml"
      - "jobs/gitlab.yml"

variables:
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  UPLOAD_PACKAGE: "false"
  PROJECT_NAME: $CI_PROJECT_NAME
  GITLAB_PROJECT_ID: "45028985"
  GITLAB_CHART_PATH: "durpapi%2FChart.yaml"

version:
  extends: .version
  stage: .pre

build:
  stage: build
  allow_failure: false
  trigger:
    include:
      - project: "developerdurp/yml"
        ref: "main"
        file:
          - "pipelines/go-build.yml"
    strategy: depend
  rules:
    - exists:
        - "go.mod"

generate-pipeline-dev:
  extends: .generate-config
  stage: build
  variables:
    ENVIRONMENT: "dev"

deploy-dev:
  stage: release
  needs:
    - job: build
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-pipeline-dev
    strategy: depend
  variables:
    ENVIRONMENT: "dev"
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

generate-pipeline-prd:
  extends: .generate-config
  stage: build
  variables:
    ENVIRONMENT: "prd"

deploy-prd:
  stage: release
  needs:
    - job: deploy-dev
    - job: generate-pipeline-prd
  when: manual
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-pipeline-prd
    strategy: depend
  variables:
    ENVIRONMENT: "prd"
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
