stages:
  - deploy

include:
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/version.yml'

variables:
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  UPLOAD_PACKAGE: "false"
  PROJECT_NAME: $CI_PROJECT_NAME

version:
  extends: .version
  stage: .pre

build:
  stage: deploy
  allow_failure: false
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/go-build.yml'
    strategy: depend
  rules:
    - exists:
      - "go.mod"  


deploy_staging:
  stage: deploy
  needs:
    - job: build
      optional: true
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
