stages:
  - deploy

include:
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/version.yml'
      - 'jobs/gitlab.yml'

variables:
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  UPLOAD_PACKAGE: "false"
  PROJECT_NAME: $CI_PROJECT_NAME

version:
  extends: .version
  stage: .pre

    #build:
    #  stage: deploy
    #  allow_failure: false
    #  trigger: 
    #    include: 
    #    - project: 'developerdurp/yml'
    #      ref: 'main'
    #      file:
    #        - 'pipelines/go-build.yml'
    #    strategy: depend
    #  rules:
    #    - exists:
    #      - "go.mod"  

generate-config:
  extends: .generate-config
  stage: deploy
    #needs:
    #  - job: build

child-pipeline:
  stage: deploy
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
