name: Package Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.7.0'

    - name: Package Helm chart
      run: helm package ./charts --version 1.0.0

    - name: Publish Helm chart package
      uses: GitHubPackages/publish-package@v1
      with:
        package_name: my-chart
        package_version: 1.0.0
        token: ${{secrets.GITHUB_TOKEN}}